---
# external roles and collections to download
# install: ansible-galaxy install -r requirements.yml

roles:
  - name: 'oxlorg.nginx'
    src: 'git+https://github.com/O-X-L/ansible-role-nginx'

  - name: 'oxlorg.docker_minimal'
    src: 'git+https://github.com/O-X-L/ansible-role-docker-minimal'

collections:
  - 'community.general'
  - 'ansible.posix'
  - 'community.docker'
