---

- name: Zabbix Server | Backup | Install MariaDB-Client
  ansible.builtin.apt:
    name: ['mariadb-client', 'xz-utils']

- name: Zabbix Server | Backup | Credentials
  ansible.builtin.copy:
    content: |
      # ansible_managed
      # ansibleguy.sw_zabbix_server
      [client]
      host = 127.0.0.1
      user = root
      password = {{ ZBX_CONFIG.db.root_pwd }}
      port = 3306
    dest: "{{ ZBX_HC.path.mariadb_client_config }}"
    mode: 0600
  no_log: true
  tags: config

- name: Zabbix Server | Backup | Adding script
  ansible.builtin.template:
    src: 'templates/usr/local/sbin/zabbix-server-backup.sh.j2'
    dest: '/usr/local/sbin/zabbix-server-backup.sh'
    owner: 'root'
    group: 'root'
    mode: 0750
  tags: config

- name: Zabbix Server | Backup | Adding service
  ansible.builtin.template:
    src: "templates/etc/systemd/system/{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    owner: 'root'
    group: 'root'
    mode: 0755
  loop:
    - 'zabbix-server-backup.service'
    - 'zabbix-server-backup.timer'

- name: Zabbix Server | Backup | Enabling/starting timer
  ansible.builtin.systemd:
    name: 'zabbix-server-backup.timer'
    enabled: true
    state: started
  when: ZBX_CONFIG.backup.enable | bool

- name: Zabbix Server | Backup | Disabling/stopping update timer
  ansible.builtin.systemd:
    name: 'zabbix-server-backup.timer'
    enabled: false
    state: stopped
  when: not ZBX_CONFIG.backup.enable | bool
  ignore_errors: true
