---

- name: Zabbix Server | Update | Adding script
  ansible.builtin.template:
    src: 'templates/usr/local/sbin/zabbix-server-update.sh.j2'
    dest: '/usr/local/sbin/zabbix-server-update.sh'
    owner: 'root'
    group: 'root'
    mode: 0750
  tags: config

- name: Zabbix Server | Update | Adding service
  ansible.builtin.template:
    src: "templates/etc/systemd/system/{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    owner: 'root'
    group: 'root'
    mode: 0755
  loop:
    - 'zabbix-server-update.service'
    - 'zabbix-server-update.timer'

- name: Zabbix Server | Update | Enabling/starting timer
  ansible.builtin.systemd:
    name: 'zabbix-server-update.timer'
    enabled: true
    state: started
  when: ZBX_CONFIG.auto_update.enable | bool

- name: Zabbix Server | Update | Disabling/stopping timer
  ansible.builtin.systemd:
    name: 'zabbix-server-update.timer'
    enabled: false
    state: stopped
  when: not ZBX_CONFIG.auto_update.enable | bool
  ignore_errors: true
